# Generated by Django 6.0.1 on 2026-01-30 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('friends_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('BLOCKED', 'Blocked')])),
                ('from_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('from_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_friend', to='friends_user.friends_user')),
                ('to_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_friend', to='friends_user.friends_user')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('from_friend', 'to_friend'), name='unique_requests'), models.CheckConstraint(condition=models.Q(('from_friend', models.F('to_friend')), _negated=True), name='prevent_self_friendship')],
            },
        ),
    ]
