# Generated by Django 6.0.1 on 2026-01-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friends_user',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('emailid', models.EmailField(max_length=200, unique=True)),
                ('phone_no', models.CharField(max_length=15, unique=True)),
                ('pfp', models.ImageField(blank=True, null=True, upload_to='user_pfp/')),
                ('info', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
